services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 1s
      retries: 1
      start_period: 5s
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 1s
      retries: 1
      start_period: 5s
    env_file:
      - .env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: yarn start
