FROM python:3.12

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY backend /app
RUN playwright install

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
