FROM python:3.12-slim 

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

RUN apt-get update && \
    apt-get install -y wget gnupg && \
    playwright install-deps && \
    python -m camoufox fetch && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY backend /app

EXPOSE 8000
CMD ["python", "main.py"]
